### ISSUE TITLE
No priority given in particular scenario

### ISSUE THREAD

**Issue by Gordon-Dry** [lolluslollus/lollo_priority_signals_1#4]
I try my best with MS Paint:
![Unbenannt](https://user-images.githubusercontent.com/29145213/232061485-e4b0f8ae-26f6-4abb-8005-dd6ff10d2b2c.png)
Both trains are moving from right to left.
The heavily loaded train on the mainline track 1 with the priority signal stopped as the empty train coming back from the station on track 3 just proceeded with vanilla behaviour.
I assume that happened because the train on track 3 was much nearer to its signal and there was another switch/junction inbetween.

**Comment by Gordon-Dry** [comment]
If  above reference is the solution, it just would need an invisible non-priority signal  - which I have installed - for the track segments between 3 to 2 and 2 to 1?

This could create other issues by blocking those intersections then.

**Comment by lolluslollus** [comment]
Add more priority signals before the one you already have on track 1.
